### ISSUE TITLE
code_gen container: its shared volume may not be shared with others

### ISSUE THREAD

**Issue by HyunwooCho** [ML-TANGO/TANGO#142]
I'm not sure how docker volume could be shared between multiple containers. 
But I noticed that the container 'code_gen' might use different volumes, not shared with others.

All other containers share a docker volume named "shared" to **/shared**.
But code_gen container has the same named volume "shared" to **/tango**.

```
  #---------------------------------
  # code_gen Build
  #---------------------------------
  code_gen:
    build:
      context: ./deploy_codegen/optimize_codegen
    hostname: codeGen
    volumes:
      - ./deploy_codegen/optimize_codegen:/source
      - shared:/tango
    command: >
      sh -c "cd /app && python3 code_gen.py"
    ports:
      - 8888:8888
 ```
