### ISSUE TITLE
Dial TCP lookup registry-1.docker.io temporary failure in name resolution Error

### ISSUE THREAD

**Issue by ML-TANGO** [ML-TANGO/TANGO#40]
If you are experiencing following error while executing `docker-compose up -d --build`;
```
Dial TCP lookup registry-1.docker.io temporary failure in name resolution Error
```
* The message means that *The Docker daemon tells us it cannot reach the docker registry*. 

The problem was solved by adding DNS entries 8.8.8.8 and 8.8.4.4.  (DNS service IP addresses from Google) to the `resolv.conf` file:
```
$ cat /etc/resolv.conf
nameserver 8.8.4.4
nameserver 8.8.8.8
```
or
 if your system uses `netplan` instead of `resolv.conf`, edit `/etc/netplan/01-network-manager-all.yaml` as follows:
```
# After editing this file, execute `sudo netplan apply`
# to reflect the chnage of nameservers
network:
  version: 2
  renderer: networkd
  ethernets:
    enp6s0:
      addresses: [xxx.xxx.xxx.xxx/24]
      dhcp4: no
      dhcp6: no
      gateway4: xxx.xxx.xxx.yyy
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
```
* `xxx.xxx.xxx.xxx` in `addrsses` means your system's ip address
* `xxx.xxx.xxx.yyy` in `gateway4` means your system's gate way address

References:
* [Solved ! - Dial TCP lookup registry-1.docker.io temporary failure in name resolution Error](https://codetryout.com/dial-tcp-lookup-registry-1-docker-io/)

**Comment by ML-TANGO** [comment]
Some of most popular DNS resolvers:
* Google (8.8.8.8, 8.8.4.4)
* Cloudflare (1.1.1.1 and 1.0.0.1)
* OpenDNS (208.67.222.222, 208.67.220.220)
* Level3 (209.244.0.3, 209.244.0.4)

DNS resolver in ETRI:
* 129.254.16.61, and 129.254.16.62
* 
DNS resolver in ETRI does not resolve outside DNS name of ETRI, from time to time. 
Hence, collaborators in ETRI are recommend to add Google DNS resolver in front of ETRI DNS resolver as follows:
```
# After editing this file, execute `sudo netplan apply`
# to reflect the chnage of nameservers
network:
  version: 2
  renderer: networkd
  ethernets:
    enp6s0:
      addresses: [xxx.xxx.xxx.xxx/24]
      dhcp4: no
      dhcp6: no
      gateway4: xxx.xxx.xxx.yyy
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4, 129.254.16.61, 129.254.16.62]
```
