### ISSUE TITLE
postgresql or db service dependency in TANGO/docker-compose.yaml, TANGO/visualization/docker-compose.yml

### ISSUE THREAD

**Issue by ML-TANGO** [ML-TANGO/TANGO#5]
In the following two files, `depend on postgresql` is ambiguous,
* TANGO/docker-compose.yml
* TANGO/visualization/docker-compose.yml

**`TANGO/docker-compose.yml`**

```yaml
services:
  #--------------------------------------------------
  # project manager developed by Teslasystems
  #--------------------------------------------------
  project_manager:
    build:
      context: ./project_manager
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata base_model_data.json &&
             python manage.py runserver 0.0.0.0:8085"
    volumes:
      - ./project_manager:/code
    ports:
      - "8085:8085"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:                          # <====== proeject_manager service depends on postgresql service here
      - postgresql

  postgresql:
    image: postgres:latest
    restart: always
    volumes:
      - postgreSQL:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
...
...
#--------------------------------------------------
# visualization (vis2code) developed by HIU
#--------------------------------------------------
  viz2code:
    build:
      context: ./visualization
    command: >
      sh -c "cd ./visualization/frontend &&
             npm run build &&
             cd ..
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8091"
    volumes:
      - ./viz2code:/source
    ports:
      - "8091:8091"
    depends_on:
      - postgresql     # <====== vis2code service depends on postgresql service here

volumes:
  postgreSQL:
```

**`TANGO/visualization/docker-compose.yml`**
```yaml
version: "3"


services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgreSQL:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=viz2code
      - POSTGRES_USER=aislab
      - POSTGRES_PASSWORD=aislab718

  viz2code:
    build:
      context: ./
    command: >
      sh -c "cd frontend &&
             npm run build &&
             cd ..
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8091"
    volumes:
      - ./viz2code:/source
    ports:
      - "8091:8091"
    depends_on:
      - db
volumes:
  postgreSQL:
```

Please give your oppinion on this situation.
